### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by peterwittek** [gsagnol/picos#13]
Do you have plans to make the code syntax comply with [PEP 8](https://www.python.org/dev/peps/pep-0008/)? That would make development easier. The tool [autopep8](https://pypi.python.org/pypi/autopep8) makes it really easy.

**Comment by gsagnol** [comment]
I did not know about autopep8, I will give it a look shortly.

**Comment by gsagnol** [comment]
I just released the 1.1.1, and
I run autopep8 to "clean the code".

The code is not 100% PEP8 compliant, but it's definitely better. Does this close the issue?

**Comment by peterwittek** [comment]
Yes, this is perfect! Thank you.
