### ISSUE TITLE
Interfaces to get primal/dual objective values and primal/dual feasiblity (amount of violation)

### ISSUE THREAD

**Issue by salbang** [gsagnol/picos#14]
It would be nice if PICOS has interfaces to retrieve primal/dual objective values and primal/dual feasibility measures (or amount of violation).
For instance, in mosek, Problem.msk_task.getprimalobj/getdualobj and Problem.msk_task.getpviolcon/getdviolcon are the relevant API functions. Thank you.

**Comment by gsagnol** [comment]
This issue is now managed under GL: https://gitlab.com/picos-api/picos/issues/14
