### ISSUE TITLE
Multiplying a matrix with a complex coefficient throws a TypeError

### ISSUE THREAD

**Issue by peterwittek** [gsagnol/picos#24]
This example works:

``` python
import cvxopt
import picos
A = cvxopt.matrix([[1.0, -1.0], [2.0, 1.0]])
problem = picos.Problem()
r = problem.add_variable('r')
problem.add_constraint(A*r == 0)
problem.solve()
```

If we add a pair of real variables to a model a complex one, it also works:

``` python
problem = picos.Problem()
r = problem.add_variable('r')
i = problem.add_variable('i')
problem.add_constraint(A*r + A*1j*i == 0)
problem.solve()
```

A single complex variable, however, throws `TypeError: invalid type in assignment`:

``` python
problem = picos.Problem()
c = problem.add_variable('c', vtype='complex')
problem.add_constraint(A*c == 0)
problem.solve()
```

I tried in both Python 2 and 3, yielding the same outcome.

**Comment by gsagnol** [comment]
I think this is simply a size problem. `A` is 2x2, so `c` must be 2 x something !
I tested the last code fragment with
`c = problem.add_variable('c', 2, vtype='complex')`
and it runs.

**Comment by peterwittek** [comment]
This turns it into a matrix-vector multiplication, but I would like to multiply a matrix with a complex constant.

**Comment by gsagnol** [comment]
ok, i get it. I'll have a look at it ASAP

**Comment by gsagnol** [comment]
... ASAP took a lot of time, sorry. This should work, now !

**Comment by peterwittek** [comment]
No luck, I still get the same error both in Python 2 and 3.

**Comment by peterwittek** [comment]
False alarm, I forgot to pull. It works great, many thanks!
