### ISSUE TITLE
Feature request: tensor (kronecker) product

### ISSUE THREAD

**Issue by ziofil** [gsagnol/picos#30]
PICOS is ideal for quantum information over other libraries because it implements complex numbers. If it had a kronecker product it would be just perfect!

Ideally, if it could mimic the functionality of numpy.einsum it would be the best, as in quantum information we often deal with tensor networks. But even a simple equivalent of numpy.kron would definitely be very welcome.

**Comment by peterwittek** [comment]
A [similar effort](https://github.com/JuliaOpt/Convex.jl/issues/57) is ongoing in `Convex.jl`, which can also do complex numbers. Nevertheless, it would be awesome to have `kron` in PICOS, since we already have partial trace and partial transpose.

**Comment by ziofil** [comment]
How can I help?

**Comment by gsagnol** [comment]
I will try to implement `kron` today. For `einsum`, it looks much more complicated.

**Comment by gsagnol** [comment]
Have a look at the new branch 'kron'

https://github.com/gsagnol/picos/pull/31

If this does what you need, I will merge the pull request.

**Comment by ziofil** [comment]
Okay, I pulled the new branch in a folder on my mac. Now, how do I tell python to import that instead of the usual anaconda module?

Done. I uninstalled the other version (1.1.2) and the new one is active. Gonna try it out now!

**Comment by ziofil** [comment]
There is an issue: even though 
`pic.__version__`
`'1.1.3.dev'`

when I try your code
`import picos as pic`
`import cvxopt as cvx`
`import numpy as np`
`P = pic.Problem()`
`X = P.add_variable('X',(4,3))`
`X.value = cvx.matrix(range(12),(4,3))`
`I = pic.new_param('I',np.eye(2))`
`pic.kron(I,X)`

I get 
`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`<ipython-input-5-eb50f466a01b> in <module>()`
`      6 X.value = cvx.matrix(range(12),(4,3))`
`      7 I = pic.new_param('I',np.eye(2))`
`----> 8 pic.kron(I,X)`

`AttributeError: module 'picos' has no attribute 'kron'`

**Comment by gsagnol** [comment]
you should pull the new branch, 
`git pull origin kron`
then, checkout the kron branch in your local repo
`git checkout kron`

After this run picos **from inside your local picos folder**. This should ensure that `import picos` imports the version in your local folder, instead of your global anaconda installation.

To check which version of picos python is using, do the following:
```
import picos as pic
pic.__file__
```
This will output the path to the picos module python is using. If it points to something inside your local repo, it should be working. Otherwise, it means that python is still using the usual anaconda package.

**Comment by peterwittek** [comment]
It works like a charm in both Python 2 and 3, thanks a lot. If you disregard the problem with partial trace in Python 3 (issue #4), you can see that the partial trace recovers the original quantum states:

```python
from __future__ import print_function
import picos as pic
import cvxopt as cvx
import numpy as np
P = pic.Problem()
X = P.add_variable('X',(2,2))
X.value = cvx.matrix([[0.09942819, 0.29923607], [0.29923607, 0.90057181]], (2, 2))
I = pic.new_param('I', [[1, 0], [0, 0]])
print(pic.kron(X, I))
print(pic.partial_trace(pic.kron(X, I), 0))
print(pic.partial_trace(pic.kron(X, I), 1))
```
Maybe you can make a unit test of this.

**Comment by ziofil** [comment]
Guys, I am loading the local file, but for some weird reason it doesn't see the new function. I even uninstalled the anaconda picos package. What can it be??
By the way, if I use python from the terminal it works, it's the jupyter notebook that is not loading the new function.

**Comment by gsagnol** [comment]
Can you please tell me what is the output of `pic.__file__`, and the content of the file  `__init__.py` towards which `pic.__file__` is pointing ?

**Comment by ziofil** [comment]
Even though the file was the right one, the module that was being loaded was like a frozen version of the old one. After restarting the notebook server it loaded the right module! And it works, thank you!
