### ISSUE TITLE
Cannot concatenate results of partial_trace

### ISSUE THREAD

**Issue by ziofil** [gsagnol/picos#33]
```import picos as pic
import numpy as np
P = pic.Problem()
B = pic.new_param('B',np.identity(4))

pic.partial_trace(B)&pic.partial_trace(B)
```

says: `UnboundLocalError: local variable 'retmat' referenced before assignment` at line `1292` of `tools.py`.

**Comment by gsagnol** [comment]
OK, now this error is intercepted and `np.int64` are cast as `int` inside `picos.tools.spmatrix`.
