### ISSUE TITLE
PySCIPOpt rather than python-zibopt?

### ISSUE THREAD

**Issue by stephane-caron** [gsagnol/picos#34]
Hi,

I spent a painful moment installing [python-zibopt](https://code.google.com/archive/p/python-zibopt/) (to use SCIP). The project is not maintained and installing it along with the latest SCIP Optimization Suite requires extensive patching. (In case it can be useful to someone else: apply this patch [python-zibop-patch.txt](https://github.com/gsagnol/picos/files/763159/python-zibop-patch.txt) ([source](http://listserv.zib.de/pipermail/scip/2013-September/001651.html)), then include all SCIP headers at the top of ``ext/python_zibopt.h``)

Maybe you can consider replacing this dependency by [PySCIPOpt](https://github.com/SCIP-Interfaces/PySCIPOpt), which is actively maintained and much easier to install?

Best,

**Comment by gsagnol** [comment]
Sure, this is currently in development. python-zibopt will not be supported anymore in the next release.

Actually, it is already implemented with PySCIPOPT in the dev-version available on github,
although a few features are still missing (in particular, picos does not retrieve optimal dual variables yet).

**Comment by mjstahlberg** [comment]
My reimplementation of SCIP via PySCIPOpt does retrieve duals in the case of LPs, which appears to be the only case in which dual information is available as far as I understand it. However, this feature depends on https://github.com/SCIP-Interfaces/PySCIPOpt/issues/136 being fixed.

**Comment by gsagnol** [comment]
This issue is now managed under GL: https://gitlab.com/picos-api/picos/issues/34
