### ISSUE TITLE
Bug in _retrieve_matrix (or in partial trace)

### ISSUE THREAD

**Issue by ziofil** [gsagnol/picos#38]
Define a variable, and its partial trace like so

```python
import picos as pic
P = pic.Problem()
R = P.add_variable('R',(4,4),'hermitian')
S = pic.partial_trace(R,k=1,dim=(2,2))
```

we can call `R.H`, but not `S.H`: 

```python
/Users/filippo/anaconda3/lib/python3.5/site-packages/picos/tools.py in _retrieve_matrix(mat, exSize)
   1290     # make sure it's sparse
   1291     if not isinstance(mat, cvx.base.spmatrix):
-> 1292         retmat = cvx.sparse(retmat)
   1293 
   1294 

UnboundLocalError: local variable 'retmat' referenced before assignment
```

**Comment by ziofil** [comment]
Following @gsagnol suggestion, I checked that this is a py3 bug, not py2.

**Comment by gsagnol** [comment]
I had a different problem with your conde snippet, when I call `S.H` in python3, it printed a `TypeError` without raising it (?).
It has been corrected, by forcing the size of AffineExpression to be `int`s (and not `np.int64`s, which cvxopt do not like).
Can you check that it solves your problem, too ?
