### ISSUE TITLE
Importing SDPA(RA) output file

### ISSUE THREAD

**Issue by IgnacioRubioScola** [gsagnol/picos#39]
The problem.write_to_file() function helps to create the 'mysdp.dat-s', then I could successfully solve the problem on a cluster (using mpirun ./sdpara mysdp.dat-s mysdp.out), but I don't know how to recover in PICOS the information from mysdp.out (I just see 3 matrices (x,X,Y)). I'm very new in python, I see that _sdpa_solve() can read the temporary mysdp.out of SDPA and mysdp.solve() gives then the resulting variables names with its value, solution of the problem. Is it possible to create a method for problem.py to just read the myspd.out instead of trying to solve the problem (that have already been solved outside python)? Thank you very much in advance!

**Comment by peterwittek** [comment]
This makes a lot of sense. I just opened PR #40 to implement this. Please try it: there is a new optional parameter for SDPA to read a solution from a file.

```python
import picos
problem = picos.Problem()
# Define the problem here
# ...
problem.write_to_file('whatever.dat-s')
# Solve externally, then read back the solution.
solution = problem.solve(solver='sdpa', sdpa_params={'read_solution': 'whatever.out'})
```
I tried it on the maxcut example and it seems to be working.

**Comment by gsagnol** [comment]
Thanks, I close the issue !
