### ISSUE TITLE
Partial Trace needed

### ISSUE THREAD

**Issue by ghost** [gsagnol/picos#4]
In order for PICOS to be useful for Quantum Information SDPs , the PARTIAL TRACE function must be implemented.

**Comment by peterwittek** [comment]
Could you also give an example with the expected result? That would help us testing. Thanks.

**Comment by gsagnol** [comment]
For the sake of  consistency with the `partial_transpose` function,
I would propose to write a function with the following signature:

`Y = partial_trace(X,dim=None)`

where :
- `X` is a matrix affine expression
- The argument `dim` is a tuple that specifies the size of the subblocks of `X`. So dim[0] must divide X.size[0] and dim[1] must divide X.size[1]
- The default `dim = None` assumes that X is of size `n^2 x n^2`, with blocks of size `n x n` for some integer `n`.
- It is allowed to give an integer parameter for dim; `dim = k` must be interpreted as `dim = (k,k)`
- The output `Y` is a matrix affine expression of size `m_1 x m_2`, where `m_i = X.size[i] / dim[i]` (i=1..2).
- The (i,j) element of `Y` is the trace of the (i,j)-block of `X`

@qubix12, can you confirm that such a function would suit your needs ?

**Comment by ghost** [comment]
One thing I would add to it is an option to select with respect to which
subsystem you want to take the partial trace. So if you have a matrix that
is a tensor product of two other matrices (2 qubit case) , there are two
possibilities to take the partial trace:

http://s10.postimg.org/tw407gmvt/ptrace.jpg

So I think the new function should be something like:

Y = partial_trace(X, j ,dim=None)

where j specifies the system with respect to which you take the partial
trace.

Would be amazing if you can implement this. I am also trying to do it, but
now I am just reading through your code, trying to understand it, and it
will take me some time. I need it somewhat urgently. :(

Thank you so much for your help with this.

Best,

Marius

**Comment by gsagnol** [comment]
OK, so I will try to do it by tomorrow.
Please confirm that I'm right, I have been trying to translate what you were explaining about tensor products in "raw operations":
- If `j=2` [default], the (i,j) element of `Y` is the trace of the (i,j)-block of `X`
- If `j=1`, then the (i,j) element of `Y`is the sum of the (i,j)-elements of the diagonal blocks of `X`.

**Comment by ghost** [comment]
Yes, but the problem is that this function must work for any dimension and
any number of subsystems, for example for

A = X1 tensor X2 tensor X3 ..... tensor Xn

one must be able to take partial_trace(A, k) where k can be anything
between 1 and n (i.e. with respect to any of the n subsystems).

I am thinking of a way to write this partial trace in a general manner. If
I manage to do that, I'll post it here.

**Comment by ghost** [comment]
So I think this is a way in which the partial trace can be generalized as I
was asking above:

http://s18.postimg.org/xqw056j6x/part_tra.jpg

Hope you understand my handwriting, I only had time to sketch on a piece of
paper the main idea.

**Comment by gsagnol** [comment]
Just to be sure I got it right, is this formula true :

If X = A1 tensor A2 tensor ... tensor AN (for me, because I work with matrices, the tensor product is the same thing as the Kronecker product, right ?)

Then tr_k(X) = trace(A_k)  A1 tensor ... A_{k-1} tensor A_{k+1} .. A_N

If this is true, then I would propose to use the following signature:

Y = partial_trace(X,k=2,dim=None)
where dim = None automatically assumes that X is the Kronecker product of 2 matrices of the same size, i.e. X is of size n^2 x n^2.
Otherwise, dim must be a tuple (n1,...,n2), such that the matrices Ai involved in the tensor product
defining X is of size ni x ni.

**Comment by ghost** [comment]
Yes, Kronecker and Tensor product are one and the same.

That formula seems to be correct. I tried it for a few cases and it gives
what I'd expect.

**Comment by gsagnol** [comment]
I just pushed a new version with a first implementation of partial_trace (cf. documentation in [docstring](https://github.com/gsagnol/picos/blob/master_github/picos/tools.py#L550-583) ).

Can you give it a look ?

Can you make some tests for n>=3, and ideally add one such example in the example of the docstring?

**Comment by ghost** [comment]
Seems to work beautifully for the 8x8 case, there Y = A1 tensor A2 tensor
A3 . Thank you so much, you saved me quite a lot of work.

**Comment by peterwittek** [comment]
Partial trace gives me a memory error:

```python
P = pic.Problem()
X = P.add_variable('X',(4,4))
X.value = cvx.matrix(range(16),(4,4))
print(pic.partial_trace(X))
```

**Comment by gsagnol** [comment]
Hi,
the same code gives me
`[ 5.00e+00  2.10e+01]`
`[ 9.00e+00  2.50e+01]`

without throwing an error. Are you using the latest development version of github ?

**Comment by peterwittek** [comment]
This is nasty. Python 2 gives the correct response, the one you got. Python 3 (tried versions 3.5.2 and 3.6.0) throws `MemoryError`. For the record, Cvxopt is version 1.1.9.

**Comment by ziofil** [comment]
For what is worth, I too get the memory error when I use the partial trace.

**Comment by gsagnol** [comment]
Yes, Peter told it is a python3-related error, I will try to have a look at it.

**Comment by peterwittek** [comment]
This was due to a perfectly absurd type error. Cvxopt in Python 3 does not accept numpy int types as indices, only raw Python int values. See PR #32.

**Comment by gsagnol** [comment]
Ahhh, thanks !
