### ISSUE TITLE
Partial_trace bug in python3

### ISSUE THREAD

**Issue by jeppe742** [gsagnol/picos#44]
Hi.

Using the partial_trace when running the following example in python 3.4 gives a `MemoryError` . It works when using python 2.

`import picos as pic`
`problem = pic.Problem()`
`x = problem.add_variable('x',(4,4),'hermitian')`
`a = pic.partial_trace(x,0,(2,2))`

The output is:
` ...lib\site-packages\picos\expression.py in partial_trace(self, k, dim)`
`       830`
`       831                     colij_l = col_l * pdim + row_l`
`--> 832                     fact[rowij, colij_l] = 1`
`      833`
`      834         newfacs = {}`

`MemoryError:`

After stepping into the code, it seems like it is caused by `rowij` and `colij_l` not being pure ints, but numpy objects or something. Simply casting them to ints as the following, solves the problem:

`fact[int(rowij), int(colij_l)] =1`

Thanks.

**Comment by peterwittek** [comment]
Are you using the git version? This was resolved in PR #32, and issue #33 is also about this.

**Comment by jeppe742** [comment]
I was using v.1.1.2

When upgrading to the git version, the error is gone, but now i get the following error.

`c:\temp\picos\picos\expression.py in partial_trace(self, k, dim)`
`    876         else:`
`    877             cons = None`
`--> 878         return AffinExp(newfacs, cons, (pdimred[0],pdimred[1]), 'Tr_' + str(k) + '(' + self.string + ')')`
 `   879`
 `   880     def hadamard(self, fact):`

`c:\temp\picos\picos\expression.py in __init__(self, factors, constant, size, string)`
`    246         print(_is_integer(size[0]))`
`    247         print(_is_integer(size[1]))`
`--> 248         assert len(size)==2 and _is_integer(size[0]) and _is_integer(size[1])`
`    249         #make sure they are of class int, otherwise compatibility problem with py3...`
`    250         self._size = (int(size[0]), int(size[1]))`
`AssertionError:`

If i get the type of `size[0]` and `size[1]`, they're both `np.int32` for some reason, and as far as i can see, `_is_integer` only checks for `np.int64`.
Including a check for `isinstance(x,np.int32)` in `_is_integer` solves the problem.

Best Regards

**Comment by gsagnol** [comment]
Thanks for reporting it, I will submit upload a new version including a 
check test for int32.

Best,

Guillaume.

**Comment by gsagnol** [comment]
Done.
