### ISSUE TITLE
geomean objective not supported?

### ISSUE THREAD

**Issue by lorenz-halt** [gsagnol/picos#49]
Hi,
I am trying to define a sdp with an geomean objective. But geomean return a specialized Expression type, which is not in the "isinstance-testing".

Am I getting something wrong here or were these instances just forgotten in the type-checking?

Thanks for you help!

BTW: Great package!

Here is the minimal example:
```python
## geomean objective testcase ##
import picos as pic
import numpy as np
from numpy import linalg as LA
n = 3

### PICOS Definitions 
# Constants
II = pic.new_param('I', np.eye(n))

# Problem
prob = pic.Problem()

# Parameters
QQ = prob.add_variable('Q', (n, n), vtype='symmetric')

# Objective
## Exception: unsupported objective
#prob.set_objective('max', pic.detrootn(QQ))
prob.set_objective('min', pic.geomean(QQ))

## objective ok
#prob.set_objective('min', pic.trace(QQ))

prob.add_constraint(QQ>>II)

# Output
print prob
prob.solve(verbose=0, solver='cvxopt')
print "Q:\n", QQ
print "eig:\n", LA.eigvals(QQ.value)
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-8-1cd7995a1def> in <module>()
     18 ## Exception: unsupported objective
     19 #prob.set_objective('max', pic.detrootn(QQ))
---> 20 prob.set_objective('min', pic.geomean(QQ))
     21 
     22 ## objective ok

/usr/local/lib/python2.7/dist-packages/picos/problem.pyc in set_objective(self, typ, expr)
    433         if not (isinstance(expr, AffinExp) or isinstance(expr, LogSumExp)
    434                 or isinstance(expr, QuadExp) or isinstance(expr, GeneralFun)):
--> 435             raise Exception('unsupported objective')
    436         if isinstance(self.objective[1], LogSumExp):
    437             oldexp = self.objective[1]

Exception: unsupported objective

**Comment by martindvds** [comment]
Does the error persist when you create an equivalent problem where you put the geomean into a constraint?
Like so:

```
s = prob.add_variable('s', 1)
prob.add_constraint(pic.geomean(QQ) < s)
prob.set_objective('min', s)
```

**Comment by lorenz-halt** [comment]
With the above changes I got an "unexpected mat variable" Error:
```python
# Parameters
QQ = prob.add_variable('Q', (n, n), vtype='symmetric')
ss = prob.add_variable('s', 1)

# Objective
prob.set_objective('min', ss)

prob.add_constraint(pic.geomean(QQ) < ss)
#prob.add_constraint(pic.detrootn(QQ) < ss)
````
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-32-66490835a717> in <module>()
     21 prob.set_objective('min', ss)
     22 
---> 23 prob.add_constraint(pic.geomean(QQ) < ss)
     24 #prob.add_constraint(ss < pic.detrootn(QQ))
     25 

/usr/local/lib/python2.7/dist-packages/picos/expression.pyc in __gt__(self, exp)
   1469             return exp < self
   1470         else:
-> 1471             term, termString = _retrieve_matrix(exp, self.size)
   1472             exp2 = AffinExp(
   1473                 factors={},

/usr/local/lib/python2.7/dist-packages/picos/tools.pyc in _retrieve_matrix(mat, exSize)
   1284         retmat *= alpha
   1285     else:
-> 1286         raise NameError('unexpected mat variable')
   1287 
   1288     # make sure it's sparse

NameError: unexpected mat variable


---------------------------------------------------------------------------

However this worked (but I am not sure if this is an equivalent problem):
```python
## geomean objective testcase ##
import picos as pic
import numpy as np
from numpy import linalg as LA
n = 3

### PICOS Definitions 
# Constants
II = pic.new_param('I', np.eye(n))

# Problem
prob = pic.Problem()

# Parameters
QQ = prob.add_variable('Q', (n, n), vtype='symmetric')
ss = prob.add_variable('s', 1)

# Objective
prob.set_objective('max', ss)

prob.add_constraint(ss < pic.geomean(QQ))
#prob.add_constraint(ss < pic.detrootn(QQ))

prob.add_constraint(QQ>>0) # no solution with QQ>>II

# Output
print prob
prob.solve(verbose=0, solver='cvxopt')
print "Q:\n", QQ
print "eig:\n", LA.eigvals(QQ.value)
```

**Comment by gsagnol** [comment]
Here is the problem:
geomean and detrootn are CONCAVE functions.

So maximizing a geomean (or detrootn) is a convex optimization problem, but minimizing a geometric mean is a non-convex problem, which cannot be handled with picos. Obviously, the two versions above are NOT equivalent problems (maximizing or minimizing is not the same).

If your problem is to maximize the geomean, then as  @martindvds suggested, you have to introduce an auxiliary variable, so the geometric mean is handled as a constraint. This is what you did in the example above.

**Comment by lorenz-halt** [comment]
Thanks for clarification. I did not only change min and max, but also the additional constraint. I hope my comment does not seem that stupid anymore.

However, Is there a forum or newsgroup where I can get in contact with you professionals? I see, that github issues are not the right place for such discussions.

Thanks!
