### ISSUE TITLE
Handling strict inequality constraints

### ISSUE THREAD

**Issue by lorenz-halt** [gsagnol/picos#50]
After reading the documentation I think that the operators (i.e. '<' and '<<') are not strict, mean they are equivalent to '<=' or '<<=' (if this makes sense).

I found several sources telling, that it is always possible to find an equivalent problem with non-strict inequalities. However, I was not able to find a instructional explanation. The only practical approach I found was to replace i.e. `P<<0` with `P<<=e*I, e<0` but this only works if `<` is strict.

Anyone some good advice? I have many rather complex SDP/LMI constraints and not the mathematical foundation to speed-read 720 pages of [Boyds Book](https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf).

Thanks,
Advices are warmly welcome :-)

**Comment by IgnacioRubioScola** [comment]
Hi,
Using P + eps * Id << 0 and P - eps * Id >> 0 should work find with eps>0 and Id the identity matrix.

**Comment by lorenz-halt** [comment]
Could eps not be equal to zero as well in this case?

**Comment by IgnacioRubioScola** [comment]
if eps=0, then it is equivalent to the initial condition P>>0 (P<<0), that means P is positive (negative) semidefinite. For numerical purposes eps should be greater than the inequalities tolerance of the solver.

**Comment by lorenz-halt** [comment]
I try to ensure that the constraint is to be positiv definit, not semi-. Now I see, that my initial comment might be not expressive enough, sorry.
