### ISSUE TITLE
absolute value in constraints setting fix values in the variables

### ISSUE THREAD

**Issue by javitr** [gsagnol/picos#54]
Hello!

I have some problems with getting the absolute value from a complex expression with PICOS, it is very weird because I previously had:

Sf = prob.add_variable('Sf', nl, vtype='complex')
prob.add_list_of_constraints([Sf[i] == w[fr[i], to[i]]*conj(yft[i])/(tr[i]**2) for i in xrange(0, nl)], 'i', 'xrange(0, nl)')
prob.add_list_of_constraints([abs(Sf[i]) <= Smax[i] for i in xrange(0, nl)], 'i', 'xrange(0, nl)')

then it returned "Exception: A constraint involves inequality between complex numbers".

Then I made the variable continuous and included the abs() function in the constraint:

Sf = prob.add_variable('Sf', nl, vtype='continuous')
prob.add_list_of_constraints([Sf[i] == abs(w[fr[i], to[i]]*conj(yft[i])/(tr[i]**2)) for i in xrange(0, nl)], 'i', 'xrange(0, nl)')
prob.add_list_of_constraints([Sf[i] <= Smax[i] for i in xrange(0, nl)], 'i', 'xrange(0, nl)')

And then it turns out that the variable has become a parameter apparently, and is not optimized when calling the solver:

[20 constraints (first: Sf[0] = 1.58124233313)]

Does anyone have an idea of why would this happen and how it could be solved? If I compute the real or imaginary values instead of absolute, then it is correctly optimized, but as soon as I make them squared to calculate real(Sf)**2 + imag(Sf)**2 it becomes a fixed number again.

Thank you for any suggestion,

Cheers

**Comment by gsagnol** [comment]
in ``abs(Sf[i]) <= Smax[i]``,
my guess is that Smax[i] is a complex number right ? Then, PICOS is right about complaining. 
Please send me a minimal example so I can check it out.

Your second idea of making `Sf` continuous should not work, because the equality constraint
`` abs (x) == y`` is not convex (unless x is a parameter), and hence not supported.

**Comment by javitr** [comment]
Thank you for your answer gsagnol.

Smax is actually a real number, a float value.


Here is a simplified code including the constraint that is giving me problems, it can be executed to test it, as it is, with the abs(S) <= Smax it gives the complex inequality error, and changing abs(S) for real(S) or imag(S) makes it work without problems...


[abs_prob.zip](https://github.com/gsagnol/picos/files/1348881/abs_prob.zip)

**Comment by mjstahlberg** [comment]
Note that even with Viech/picos@f229734a8c98ea522fcb7c47e6fcaeb19d8dd9b7, CVXOPT gives a `math domain error` after 843 iterations, while the only other solver capable of solving this type of problem, MOSEK, is broken on the parent commit (i.e. `master`).

---

The following is not essential to this issue, but it is related to the example code provided by @javitr so I log it here:

Replaying the fix on my `refactor/solvers` branch produces a weird issue where `add_list_of_constraints` passes a `numpy.ndarray` to `add_constraint` as `[abs(Sf[i]) <= Smax[i] for i in xrange(0, nl)]` evaluates to
```
[array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]), array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ True]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])]
```
both with and without the fix. On master without my fix it is
```
[# (2x1)-affine constraint: ||Sf[0]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[1]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[2]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[3]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[4]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[5]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[6]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[7]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[8]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[9]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[10]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[11]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[12]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[13]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[14]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[15]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[16]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[17]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[18]|| < 99.0 #, # (2x1)-affine constraint: ||Sf[19]|| < 99.0 #]
```
and with my fix it is
```
[# (2x1)-SOC constraint: ||[0.5*( Sf[0] + Sf[0].conj );( -0.5j )*( Sf[0] -Sf[0].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[1] + Sf[1].conj );( -0.5j )*( Sf[1] -Sf[1].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[2] + Sf[2].conj );( -0.5j )*( Sf[2] -Sf[2].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[3] + Sf[3].conj );( -0.5j )*( Sf[3] -Sf[3].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[4] + Sf[4].conj );( -0.5j )*( Sf[4] -Sf[4].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[5] + Sf[5].conj );( -0.5j )*( Sf[5] -Sf[5].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[6] + Sf[6].conj );( -0.5j )*( Sf[6] -Sf[6].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[7] + Sf[7].conj );( -0.5j )*( Sf[7] -Sf[7].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[8] + Sf[8].conj );( -0.5j )*( Sf[8] -Sf[8].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[9] + Sf[9].conj );( -0.5j )*( Sf[9] -Sf[9].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[10] + Sf[10].conj );( -0.5j )*( Sf[10] -Sf[10].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[11] + Sf[11].conj );( -0.5j )*( Sf[11] -Sf[11].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[12] + Sf[12].conj );( -0.5j )*( Sf[12] -Sf[12].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[13] + Sf[13].conj );( -0.5j )*( Sf[13] -Sf[13].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[14] + Sf[14].conj );( -0.5j )*( Sf[14] -Sf[14].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[15] + Sf[15].conj );( -0.5j )*( Sf[15] -Sf[15].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[16] + Sf[16].conj );( -0.5j )*( Sf[16] -Sf[16].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[17] + Sf[17].conj );( -0.5j )*( Sf[17] -Sf[17].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[18] + Sf[18].conj );( -0.5j )*( Sf[18] -Sf[18].conj )]|| < 99.0 #, # (2x1)-SOC constraint: ||[0.5*( Sf[19] + Sf[19].conj );( -0.5j )*( Sf[19] -Sf[19].conj )]|| < 99.0 #]
```
I have not the slightest clue how my refactorings would cause this, as both the old and the new implementation of `add_list_of_constraints` would just iterate over the provided list and pass it to `add_constraint`. Somehow that list evaluates to a different type now.

Hence, I couldn't test with the fixed version of MOSEK.
