### ISSUE TITLE
minimize a norm

### ISSUE THREAD

**Issue by duyvuleo** [gsagnol/picos#55]
Hi,

I would like to do a minimization of a norm. I tried the following but got error messages from picos.

Code:
```
import picos as pic
import cvxopt as cvx

# generate/load data (possibly from file)
# size of the data
# FIXME: data from file
L = 10 # number of relaxed variables
Dy = 82 # number of output symbols (target vocabulary size)
Yh_sgd = cvx.matrix(xrange(L*Dy), (Dy,L))

# creates a problem and the optimization variables
prob = pic.Problem()
Yh = prob.add_variable('Yh', (Dy, L)) # Yh is a matrix of L Dy-dimensional relaxed variables 

# convert the constants into params of the problem
Yh_sgd = pic.new_param('Yh_sgd', Yh_sgd) # now an expression

# add the constraints
prob.add_list_of_constraints( [ Yh[0:Dy-1,i] << pic.simplex(1) for i in range(L) ], ['i'], '[L]' ) # simplex constraints

# set the objective
o = 1.0/2.0 * pic.sum([ abs(Yh[:,i] - Yh_sgd[:,i]) for i in range(L) ], #summands
                            'i',    #name of the index
                            '[L]'   #set to which the index belongs
                           )
prob.set_objective('min',  o) 

# display the problem
print prob
```
Error message: 

> Traceback (most recent call last):
>   File "<stdin>", line 4, in <module>
>   File "/home/vhoang2/.local/lib/python2.7/site-packages/picos/tools.py", line 154, in sum
>     if 'z' in [m.typecode for exp in lst for m in exp.factors.values()
> AttributeError: 'Norm' object has no attribute 'factors'

I am looking forward to your advice! Thanks!

--
Cheers,
Vu

**Comment by gsagnol** [comment]
Only a few nonlinear objectives are supported. You should put your norm in a constraint instead:
So, you should add an auxiliary variable `t` ,
put a constraint `o<=t`
and minimize the new objective function `t`.

**Comment by duyvuleo** [comment]
Hi,
Thanks. It will work for one norm, but I want a sum of norms, e.g., 
```
prob.add_constraint( 1.0/2.0 * pic.sum([ abs(Yh[:,i] - Yh_sgd[:,i]) for i in range(L) ], #summands
                            'i',    #name of the index
                            '[L]'   #set to which the index belongs
                           ) <= t )
```
We still could not use a norm within a sum, right?

**Comment by duyvuleo** [comment]
I also tried another approach, referring to #29 , but it did not work as well. The error message is as follows:
```
prob.add_constraint( 1.0/2.0 * pic.sum([ (Yh[:,i] - Yh_sgd[:,i]).T * (Yh[:,i] - Yh_sgd[:,i]) for i in range(L) ], #summands
                            'i',    #name of the index
                            '[L]'   #set to which the index belongs
                           ) <= o )
```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/vhoang2/.local/lib/python2.7/site-packages/picos/tools.py", line 154, in sum
>     if 'z' in [m.typecode for exp in lst for m in exp.factors.values()
> AttributeError: 'QuadExp' object has no attribute 'factors'

**Comment by gsagnol** [comment]
For a sum of norms, create a variable ``z[i]`` for each norm, such that
``abs(Yh[:,i] - Yh_sgd[:,i]) < z[i]``
and then add the constraint
``1.0/2.0 * (1|z) <= o``

Note: (1|z) is a shorthand for the sum of the z[i]'s

**Comment by duyvuleo** [comment]
@gsagnol : what should I do if I want a square of norm-2? Thanks!

**Comment by gsagnol** [comment]
Same as above:
create a variable `t`, add a constraint of the form
``abs(x)**2 < t``
and then minimize `t`

**Comment by duyvuleo** [comment]
Great. Thanks!
