### ISSUE TITLE
Constraint creation too slow

### ISSUE THREAD

**Issue by pgrandinetti** [gsagnol/picos#56]
Hi,
I've got a variable of dimensions 2600x2600 (roughly). To create a constraint over the sum of each row I did the following
```
import picos, numpy
prob = picos.Problem()
var = prob.add_variable('var', (2600,2600))
ones = picos.new_param(name='1', value=numpy.ones(2600,))
prob.add_constraint(var*ones <= 100)
```
This short code should be reproducible. The interpreter just gets stuck on the last line: I am guessing creating the constraint this way is very slow in picos (then again, why?).
Is there a more clever way to achieve it?
Cheers

**Comment by gsagnol** [comment]
Hi,
thanks for reporting this issue, this is probably due to some bad implementation of the multiplication of affine expression. We will look into it.
Best,

**Comment by gsagnol** [comment]
This issue is now tracked under GL https://gitlab.com/picos-api/picos/issues/56
