### ISSUE TITLE
Knowing the value of a constraint after solving the problem.

### ISSUE THREAD

**Issue by IgnacioRubioScola** [gsagnol/picos#60]
How can I recover the value of a constraint after solving a problem? I need to verify that all the constraints were satisfied.
Does exist something like prob.constraint[i].value?
Thanks in advance,
Ignacio

**Comment by gsagnol** [comment]
There is an attribute prob.constraint[i].slack,
which should be nonnegative when the constraint is satisfied.

There is also a function prob.check_current_value_feasibility()
which checks whether all constraints are satisfied, and returns something like the amount of constraint violation.
