### ISSUE TITLE
In-place addition of AffinExp fails to produce correct string representation.

### ISSUE THREAD

**Issue by mjstahlberg** [gsagnol/picos#62]
The following code adds a constant `AffinExp` of `|2|` (`RHS`) to an `AffinExp` of `X -|2.0|` (`LHS`):
```
print("LHS type:", type(LHS), "\nRHS type:", type(RHS), "\nRHS String:", RHS)
print("Before adding RHS to LHS:")
print("LHS String:", LHS, "\nLHS Constant:", LHS.constant)
LHS += RHS
print("After adding RHS to LHS:")
print("LHS String:", LHS, "\nLHS Constant:", LHS.constant)
```

The internal representation of `LHS` changes to have a constant term of `0`, as it should, but its string representation still reads `X -|2.0|`:

> LHS type: <class 'picos.expression.AffinExp'> 
> RHS type: <class 'picos.expression.AffinExp'>
> 
> RHS String: [ 2.00e+00  2.00e+00]
> [ 2.00e+00  2.00e+00]
> 
> Before adding RHS to LHS:
> LHS String: # (2 x 2)-affine expression: X -|2.0| # 
> LHS Constant: [-2.00e+00]
> [-2.00e+00]
> [-2.00e+00]
> [-2.00e+00]
> 
> After adding RHS to LHS:
> LHS String: # (2 x 2)-affine expression: X -|2.0| # 
> LHS Constant: [ 0.00e+00]
> [ 0.00e+00]
> [ 0.00e+00]
> [ 0.00e+00]

**Comment by gsagnol** [comment]
This issue is now tracked under GL https://gitlab.com/picos-api/picos/issues/62
