### ISSUE TITLE
Inconsistent representation of zero in AffinExp.constant.

### ISSUE THREAD

**Issue by mjstahlberg** [gsagnol/picos#63]
There are several ways to create a constant zero matrix `AffinExp`:
- `AffinExp(size=(2,2), constant=0)`
- `AffinExp(size=(2,2)) + 0`
- `AffinExp(size=(2,2))`

However, the string representation of the first is different from the second and third and, more importantly, they all differ in their `constant` member:

```
for s in (
    "AffinExp(size=(2,2), constant=0)",
    "AffinExp(size=(2,2)) + 0",
    "AffinExp(size=(2,2))"):
    print("-"*len(s))
    print(s)
    print("-"*len(s))
    e = eval(s)
    print("String representation:")
    print(e)
    print("Constant term:")
    print(e.constant)
    print()
```

```
--------------------------------
AffinExp(size=(2,2), constant=0)
--------------------------------
String representation:
[ 0  0]
[ 0  0]

Constant term:
0

------------------------
AffinExp(size=(2,2)) + 0
------------------------
String representation:
[ 0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00]

Constant term:
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]


--------------------
AffinExp(size=(2,2))
--------------------
String representation:
[ 0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00]

Constant term:
None
```

I suggest that
- a constant given via the `constant` parameter should either be required to have the proper dimension or be broadcasted to it, and
- an `AffinExp` without an explicit constant should have a constant of zero of proper dimension, so that in no case the constant is `None`.

**Comment by gsagnol** [comment]
This issue is now tracked under GL https://gitlab.com/picos-api/picos/issues/63
