### ISSUE TITLE
Inconsistent categorization of quadratic programs.

### ISSUE THREAD

**Issue by mjstahlberg** [gsagnol/picos#64]
Let there be three classes of continuous quadratic programs that can be input to PICOS;
- QP (only the objective function is quadratic),
- QCP (only some constraints are quadratic),
- QCQP (both the objective function and some constraints are quadratic).

Then PICOS would call both QCP and QCQP a _QCQP_.

Analogously, let there be three classes of mixed integer quadratic programs that can be input to PICOS;
- MIQP (only the objective function is quadratic),
- MIQCP (only some constraints are quadratic),
- MIQCQP (both the objective function and some constraints are quadratic).

Then PICOS would call both MIQCP and MIQCQP a _MIQCP_.

This behaviour is
- inconsistent between continuous and mixed integer problems and
- sensitive in the sense that quadratic terms within the objective function and the constraints are distinguished but insensitive in the sense that the three possible combinations are not distinguished.

As long as quadrativ objectives are stored as such (and not transformed into a linear objective and a quadratic constraint immediately), I suggest distinguishing all six classes defined above. Thoughts @gsagnol?

**Comment by gsagnol** [comment]
I would leave out QCP (which I guess is as difficult as QCQP from the point of view of algorithms).
So, let us be consistent, and use QP, QCQP, MIQP, and MIQCQP.

**Comment by gsagnol** [comment]
This issue is now tracked under GL https://gitlab.com/picos-api/picos/issues/64
