### ISSUE TITLE
partial transpose issue

### ISSUE THREAD

**Issue by ghost** [gsagnol/picos#9]
Could you please modify the partial_transpose(exp, dim=None) such that it can also transpose with respect to a certain number of tensor product elements? 

For example 

A = B1 tensor B2 tensor B3 tensor B4 tensor B5

and you want to take the partial transpose with respect to B2 or only to the subsystem generated by B3 tensor B4 . 

Is there a way to do this with the current implementation? 

I'd suggest something like 

partial_transpose ( exp, dim , subsys, to_be_transp) 

where exp = expression , dim = size of your entire matrix , subsys would be a tuple/list that contains the size of the subsystems (B1,B2...), and to_be_transp is a tuple of the subsystems to be transposed. For example, for the above matrix A, if the Bi's are 2x2 and you want to partially transpose over B3 tensor B4, the function call could be:

partial_transpose(A, (32,32),(2,2,2,2,2),(2,3))

the last parameter is (2,3) because (0,1,2,3,4) = (B1,B2,B3,B4,B5).

Could this be possible? 

EDIT: At the moment, the partial_transpose function can give you, at most, the following:

For M = A tensor B tensor C

the partial transpose of M with respect to C = partial_transpose(M, (2,2))
the partial transpose of M with respect to B tensor C = partial_transpose(M, (4,4))
the partial transpose of M with respect to A tensor B tensor C = partial_transpose(M, (8,8))  - this being just the full transpose. 

In the above example A, B, C are 2x2 matrices.

**Comment by gsagnol** [comment]
Hi Qubix,

I will have a look at it, I just realized that you are talking about partial_transpose, not about partial_trace anymore...

Because for partial trace, I think we can already do it by invoking partial_trace twice, 
e.g.
`pic.tools.partial_trace(pic.tools.partial_trace(X, 2,(n0,n1,n2,n3)),1,(n0,n1,n3))`
should give the partial trace of X = A0 x A1 x A2 x A3
with respect to A1 x A2.

**Comment by gsagnol** [comment]
So what is exactly needed?
Would you confirm the following formula?

if M = A0 x A1 x A2 x A3 x A4,
then the partial transpose of M with respect to A2 x A3 is
partial_transpose(M,(2,3)) := A0 x A1 x A2^T x A3^T x A4
???

Thanks !
Guillame.

**Comment by ghost** [comment]
Hi,

Sorry for replying so late.

Yes, I confirm that what you wrote above is what I actually need.

Thank you so much.

Best,

Marius

**Comment by gsagnol** [comment]
Finally I did it !
You can give it a try, and it will be part of the next release, which I plan to put online very soon.

Best !
